### ISSUE TITLE
inline-rust?

### ISSUE THREAD

**Issue by FranklinChen** [aisamanra/rust-haskell-ffi#1]
I wonder how much work it would take to create something like [`inline-c`](https://github.com/fpco/inline-c). I guess it depends on whether there is any interest from the Haskell community.

**Comment by aisamanra** [comment]
The `inline-c` module effectively re-implements its own [C parser and pretty-printer](https://github.com/fpco/inline-c/blob/master/src/Language/C/Types/Parse.hs) for a superset of C which includes 'antiquotation' (i.e. interpolation of Haskell values into the C context), and then Template Haskell which writes the appropriate file and emits code to stitch the FFI calls in. Doing a Rust analogue would, sadly, not be able to reuse much of the `inline-c` infrastructure, if any—you'd have to rewrite your own Rust parser and pretty-printer and modify all the FFI declarations, at least.

There are other issues involved—for example, the Haskell/Rust interop story is already difficult in areas like pushing algebraic data types between languages—but even at bare minimum, you'd have a great deal of work to get it started. It'd be a worthwhile project to tackle, but even `inline-c` had someone working on it for a significant amount of time for months before it had a release, so as interesting as it would be, I doubt we'll be seeing one any time soon.

**Comment by xavier83** [comment]
perhaps https://github.com/jameysharp/corrode/issues/21 could come in handy, but yes still a long way to go.

**Comment by harpocrates** [comment]
I've done this [here](https://github.com/harpocrates/inline-rust). It isn't on Hackage yet, mostly because I haven't polished it yet and it depends on my (as of yet) unmerged GHC branch.

Eventually I'll think about ADT's and such. For now, I'm happy with simple types. :)
